# Generated by Django 5.2.1 on 2025-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250525_1607'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Profile_user',
            new_name='profile_user',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Tournament',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='Profile_organizer',
            new_name='profile_organizer',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='TournamentCategory',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_categories',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.tournamentcategory', verbose_name='Категории'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('tournament', 'profile_user', 'tournament_category'), ('tournament', 'unregistered_participant', 'tournament_category')},
        ),
    ]
