# Generated by Django 5.2.1 on 2025-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_profile_user_registration_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='newbies',
            field=models.BooleanField(default=False, verbose_name='Участие новичков'),
        ),
    ]
