# Generated by Django 5.2.1 on 2025-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_newbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='early_registration_end',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='late_registration_end',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='regular_registration_end',
        ),
        migrations.AddField(
            model_name='tournament',
            name='early_registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало ранней регистрации'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='late_registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало поздней регистрации'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='regular_registration_start',
            field=models.DateTimeField(null=True, verbose_name='Начало обычной регистрации'),
        ),
    ]
