# Generated by Django 5.2.1 on 2025-05-29 01:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_tournament_early_registration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='belt_level',
            field=models.CharField(default=None, max_length=50, verbose_name='Уровень пояса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='newbies',
            field=models.BooleanField(default=False, verbose_name='Новичок'),
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='belt_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
