# Generated by Django 5.2.1 on 2025-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_organizer',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='profile_organizer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='unregisteredparticipant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
