# Generated by Django 5.2.1 on 2025-05-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_organizer_company_address_and_more'),
        ('accounts', '0002_create_user_groups'),
    ]

    operations = [
    ]
