# Generated by Django 5.2.1 on 2025-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250525_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='coach',
        ),
        migrations.AddField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='coach',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='coach',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
