# Generated by Django 5.2.1 on 2025-05-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_user_coach_coach_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='accounts.coach', verbose_name='Тренер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='coach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название клуба'),
        ),
    ]
