# Generated by Django 5.2.1 on 2025-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_club_options_remove_coach_club_club_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='club',
        ),
        migrations.AddField(
            model_name='profile_user',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.club', verbose_name='Клубы'),
        ),
    ]
