# Generated by Django 5.2.1 on 2025-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_user_club_profile_user_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredparticipant',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='unregistered_participants', to='accounts.club', verbose_name='Клубы'),
        ),
    ]
